/* eslint-disable prettier/prettier */
const icons = {
  //New Topic
  coins: require('../Assets/Icons/NewTopic/icons8Coins.png'),
  FacebookLike: require('../Assets/Icons/NewTopic/icons8FacebookLike.png'),
  Law: require('../Assets/Icons/NewTopic/icons8Law.png'),
  Listening: require('../Assets/Icons/NewTopic/icons8Listening.png'),
  Loser: require('../Assets/Icons/NewTopic/icons8Loser.png'),
  Office: require('../Assets/Icons/NewTopic/icons8Office.png'),
  Racism: require('../Assets/Icons/NewTopic/icons8Racism.png'),
  Scales: require('../Assets/Icons/NewTopic/icons8Scales.png'),
  VisualizationSkill: require('../Assets/Icons/NewTopic/icons8VisualizationSkill.png'),
  //Chat Avatar
  football: require('../Assets/Icons/AvatarIcons/football.png'),
  AirplaneModeOn: require('../Assets/Icons/AvatarIcons/icons8AirplaneModeOn.png'),
  Baseball: require('../Assets/Icons/AvatarIcons/icons8Baseball.png'),
  Commercial: require('../Assets/Icons/AvatarIcons/icons8Commercial.png'),
  Crown: require('../Assets/Icons/AvatarIcons/icons8Crown.png'),
  Cup: require('../Assets/Icons/AvatarIcons/icons8Cup.png'),
  Diamond: require('../Assets/Icons/AvatarIcons/icons8Diamond.png'),
  GameConsole: require('../Assets/Icons/AvatarIcons/icons8GameConsole.png'),
  GameController: require('../Assets/Icons/AvatarIcons/icons8GameController.png'),
  Guitar: require('../Assets/Icons/AvatarIcons/icons8Guitar.png'),
  Hammer: require('../Assets/Icons/AvatarIcons/icons8Hammer.png'),
  Headphones: require('../Assets/Icons/AvatarIcons/icons8Headphones.png'),
  Idea: require('../Assets/Icons/AvatarIcons/icons8Idea.png'),
  Micro: require('../Assets/Icons/AvatarIcons/icons8Micro.png'),
  OperaGlasses: require('../Assets/Icons/AvatarIcons/icons8OperaGlasses.png'),
  Pacman: require('../Assets/Icons/AvatarIcons/icons8Pacman.png'),
  QuickModeOn: require('../Assets/Icons/AvatarIcons/icons8QuickModeOn.png'),
  SoccerBall: require('../Assets/Icons/AvatarIcons/icons8SoccerBall.png'),
  Sport: require('../Assets/Icons/AvatarIcons/icons8Sport.png'),
  quashRacquet: require('../Assets/Icons/AvatarIcons/icons8SquashRacquet.png'),
  SummerHat: require('../Assets/Icons/AvatarIcons/icons8SummerHat.png'),
  SunGlasses: require('../Assets/Icons/AvatarIcons/icons8SunGlasses.png'),
  Support: require('../Assets/Icons/AvatarIcons/icons8Support.png'),
  TrophyCup: require('../Assets/Icons/AvatarIcons/icons8TrophyCup.png'),
  WaggonTruck: require('../Assets/Icons/AvatarIcons/icons8WaggonTruck.png'),
  WineGlass: require('../Assets/Icons/AvatarIcons/icons8WineGlass.png'),
  surfingBoard: require('../Assets/Icons/AvatarIcons/SurfingBoard.png'),
};

export default icons;
